# Use a true ARM64 base image
FROM arm64v8/debian:bullseye

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libudev-dev \
    make \
    file \
    binutils \
    ca-certificates \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /blhost

# Copy source
COPY . .

# Build the blhost binary
RUN make -C tools/blhost/gcc -j1 && \
    strip tools/blhost/gcc/Release/blhost
