name: Build blhost for AArch64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-blhost:
    name: Build Docker Image for ARM64 and Upload Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for ARM64 (load into local Docker)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.aarch64
          platforms: linux/arm64
          push: false
          tags: blhost:aarch64
          no-cache: true
          outputs: type=docker

      - name: Create container from built image
        run: |
          docker create --platform linux/arm64 --name extract blhost:aarch64

      - name: Copy blhost binary from container
        run: |
          docker cp extract:/lauszus-blhost/tools/blhost/gcc/Release/blhost ./blhost-aarch64
          docker rm extract

      - name: Upload blhost binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: blhost-aarch64
          path: ./blhost-aarch64
