name: Build blhost for AArch64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-blhost:
    name: Build Docker Image for ARM64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-blhost
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (or just build)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.aarch64
          platforms: linux/arm64
          push: ${{ secrets.DOCKERHUB_USERNAME != '' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME != '' && format('{0}/blhost:aarch64', secrets.DOCKERHUB_USERNAME) || 'blhost:aarch64' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Create container from built image
        run: |
          docker create --platform linux/arm64 --name extract blhost:aarch64

	  - name: Copy blhost binary from container
		run: |
		  docker cp extract:/blhost/validation/blhost/gcc/Release/blhost ./blhost-aarch64
		  docker rm extract

      - name: Upload blhost binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: blhost-aarch64
          path: ./blhost-aarch64

      - name: Move cache (persist between builds)
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cach

